---
development:
  cloud_name: ENV['CLOUD_NAME_CLOUDINARY']
  api_key: ENV['API_KEY_CLOUDINARY']
  api_secret: ENV['API_SECRET_CLOUDINARY']
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: ENV['CLOUD_NAME_CLOUDINARY']
  api_key: ENV['API_KEY_CLOUDINARY']
  api_secret: ENV['API_SECRET_CLOUDINARY']
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: ENV['CLOUD_NAME_CLOUDINARY']
  api_key: ENV['API_KEY_CLOUDINARY']
  api_secret: ENV['API_SECRET_CLOUDINARY']
  enhance_image_tag: true
  static_file_support: false
