---
development:
  cloud_name: enterprise
  api_key: '973212225345638'
  api_secret: h9k1olB0r6LkSUqXAcADXSIQzjk
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: enterprise
  api_key: '973212225345638'
  api_secret: h9k1olB0r6LkSUqXAcADXSIQzjk
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: enterprise
  api_key: '973212225345638'
  api_secret: h9k1olB0r6LkSUqXAcADXSIQzjk
  enhance_image_tag: true
  static_file_support: false
